In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../fma_metadata/features.csv", index_col=0, header=[0, 1, 2])

In [3]:
data.head(10)

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
2             7.180653  5.230309  0.249321  1.347620  1.482478  0.531371
3             1.888963  0.760539  0.345297  2.295201  1.654031  0.067592
5             0.527563 -0.077654 -0.279610  0.685883  1.937570  0.880839
10            3.702245 -0.291193  2.196742 -0.234449  1.367364  0.998411
20           -0.193837 -0.198527  0.201546  0.258556  0.775204  0.084794
26           -0.699535 -0.684158  0.048825  0.042659 -0.818967 -0.917123
30           -0.721487 -0.848560  0.890904  0.088620 -0.445513 -1.271170
46           -0.119708 -0.858814  2.362546  0.106584 -1.315912 -1.220354
48           -1.054053  0.932339  0.528064 -1.035338 -1.000682 -1.119304
134           0.918445  0.674147  0.577818  1.281117  0.933746  0.078177

feature                                              ...   tonnetz            \
statistics                                           ...       std
number            07        08        09         10  ...        04        05
track_id                                             ...
2           1.481593  2.691455  0.866868   1.341231  ...  0.054125  0.012226
3           1.366848  1.054094  0.108103   0.619185  ...  0.063831  0.014212
5          -0.923192 -0.927232  0.666617   1.038546  ...  0.040730  0.012691
10          1.770694  1.604566  0.521217   1.982386  ...  0.074358  0.017952
20         -0.289294 -0.816410  0.043851  -0.804761  ...  0.095003  0.022492
26         -0.901834 -0.066845 -0.291037  -0.861782  ...  0.103717  0.025541
30         -1.240190 -1.343765 -0.905600   2.671522  ...  0.141693  0.020426
46         -1.668162 -0.516033 -0.536395  11.025053  ...  0.132632  0.033212
48          1.166990 -1.002603 -1.094999  -0.725826  ...  0.141955  0.024654
134         1.199204 -0.175223  0.925482   1.438509  ...  0.058766  0.016322

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
2           0.012111   5.758890  0.459473  0.085629  0.071289  0.000000
3           0.017740   2.824694  0.466309  0.084578  0.063965  0.000000
5           0.014759   6.808415  0.375000  0.053114  0.041504  0.000000
10          0.013921  21.434212  0.452148  0.077515  0.071777  0.000000
20          0.021355  16.669037  0.469727  0.047225  0.040039  0.000977
26          0.023846  41.645809  0.250488  0.018388  0.015625  0.000000
30          0.025418   8.166595  0.546875  0.054417  0.036133  0.002441
46          0.021310  14.731083  0.223633  0.036601  0.032227  0.000000
48          0.025203  24.550789  0.371582  0.033015  0.022461  0.000000
134         0.015819   4.731087  0.419434  0.064370  0.050781  0.000000

feature
statistics      skew       std
number            01        01
track_id
2           2.089872  0.061448
3           1.716724  0.069330
5           2.193303  0.044861
10          3.542325  0.040800
20          3.189831  0.030993
26          4.690596  0.014598
30          2.244708  0.052674
46          2.848736  0.020713
48          4.406733  0.039016
134         1.806106  0.054623

[10 rows x 518 columns]

In [4]:
# extract for all fetures extract the mean 
cols_to_use = [col for col in data.columns if col[1] in ['mean'] and col[0] in ["chroma_cens"]]
data_filtered = data[cols_to_use]
data_filtered.head(1)

feature    chroma_cens                                                   \
statistics        mean
number              01        02        03        04       05        06
track_id
2               0.4743  0.369816  0.236119  0.228068  0.22283  0.221415

feature
statistics
number            07        08        09        10        11        12
track_id
2           0.229238  0.248795  0.196245  0.175809  0.200713  0.319972

In [ ]:
tracks = pd.read_csv("../fma_metadata/tracks.csv")
tracks

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN
...           ...                  ...                  ...      ...
155316          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155317          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155318          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155319          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155320          0  2017-03-26 16:22:18  2017-03-26 00:00:00      NaN

                                                                              \
         favorites     id                                        information
track_id
2                4      1                                            <p></p>
3                4      1                                            <p></p>
5                4      1                                            <p></p>
10               4      6                                                NaN
20               2      4          <p> "spiritual songs" from Nicky Cook</p>
...            ...    ...                                                ...
155316           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155317           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155318           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155319           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155320           1  22906                                                NaN

                               \
         listens     producer
track_id
2           6073          NaN
3           6073          NaN
5           6073          NaN
10         47632          NaN
20          2710          NaN
...          ...          ...
155316      1506  Monty Hall
155317      1506  Monty Hall
155318      1506  Monty Hall
155319      1506  Monty Hall
155320      7481          NaN

                                                             ...       track  \
                                                       tags  ... information
track_id                                                     ...
2                                                        []  ...         NaN
3                                                        []  ...         NaN
5                                                        []  ...         NaN
10                                                       []  ...         NaN
20                                                       []  ...         NaN
...                                                     ...  ...         ...
155316                                                   []  ...         NaN
155317                                                   []  ...         NaN
155318                                                   []  ...         NaN
155319                                                   []  ...         NaN
155320    ['ballad', 'epic', 'rockabilly', 'curse', 'hex...  ...         NaN

                                 \
         interest language_code
track_id
2            4656            en
3            1470            en
5            1933            en
10          54881            en
20            978            en
...           ...           ...
155316        122           NaN
155317        194           NaN
155318        214           NaN
155319        336           NaN
155320        972           NaN

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN
...                                                     ...     ...      ...
155316    Creative Commons Attribution-NonCommercial-NoD...     102      NaN
155317    Creative Commons Attribution-NonCommercial-NoD...     165      NaN
155318    Creative Commons Attribution-NonCommercial-NoD...     168      NaN
155319    Creative Commons Attribution-NonCommercial-NoD...     294      NaN
155320                            Attribution-NonCommercial     705      NaN

                                                                              \
         number publisher                                               tags
track_id
2             3       NaN                                                 []
3             4       NaN                                                 []
5             6       NaN                                                 []
10            1       NaN                                                 []
20            3       NaN                                                 []
...         ...       ...                                                ...
155316        3       NaN                                                 []
155317        4       NaN                                                 []
155318        6       NaN                                                 []
155319        5       NaN                                                 []
155320        7       NaN  ['ballad', 'epic', 'rockabilly', 'curse', 'hex...


                                              title
track_id
2                                              Food
3                                      Electric Ave
5                                        This World
10                                          Freeway
20                                  Spiritual Level
...                                             ...
155316                                    The Auger
155317                              Let's Skin Ruby
155318           My House Smells Like Kim Deal/Pulp
155319                      The Man With Two Mouths
155320    Another Trick Up My Sleeve (Instrumental)

[106574 rows x 52 columns]

In [14]:
tracks["track"]["genres"]

track_id
2                  [21]
3                  [21]
5                  [21]
10                 [10]
20            [76, 103]
              ...
155316             [25]
155317             [25]
155318             [25]
155319             [25]
155320    [10, 12, 169]
Name: genres, Length: 106574, dtype: object

In [16]:
tracks["track"]["genre_top"]

track_id
2         Hip-Hop
3         Hip-Hop
5         Hip-Hop
10            Pop
20            NaN
           ...
155316       Rock
155317       Rock
155318       Rock
155319       Rock
155320        NaN
Name: genre_top, Length: 106574, dtype: object

In [24]:
tracks["track"]["genres_all"]

track_id
2                      [21]
3                      [21]
5                      [21]
10                     [10]
20        [17, 10, 76, 103]
                ...
155316             [25, 12]
155317             [25, 12]
155318             [25, 12]
155319             [25, 12]
155320     [169, 10, 12, 9]
Name: genres_all, Length: 106574, dtype: object

In [6]:
subsets = tracks["set"]["subset"]
small_tracks = tracks[tracks["set"]["subset"] == "small"]

In [7]:
small_tracks

            album                                                            \
         comments         date_created        date_released        engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00             NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00             NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00             NaN
140             1  2008-11-26 01:49:59  2007-05-22 00:00:00             NaN
141             0  2008-11-26 01:49:57  2009-01-16 00:00:00             NaN
...           ...                  ...                  ...             ...
154308          0  2017-03-05 04:57:38  2017-03-05 00:00:00             NaN
154309          0  2017-03-05 04:57:38  2017-03-05 00:00:00             NaN
154413          0  2017-03-07 18:44:11                  NaN  Ernie Indradat
154414          0  2017-03-07 18:44:11                  NaN  Ernie Indradat
155066          0  2017-03-24 19:40:34  2017-03-24 00:00:00        JBlanked

                                                                              \
         favorites     id                                        information
track_id
2                4      1                                            <p></p>
5                4      1                                            <p></p>
10               4      6                                                NaN
140              1     61  <p>Alec K. Redfearn &amp; The Eyesores: Ellen ...
141              1     60  <p>A full ensamble of strings, drums, electron...
...            ...    ...                                                ...
154308           0  22780                                                NaN
154309           0  22780                                                NaN
154413           0  22789  <p>A live performance at WFMU for Dark Night o...
154414           0  22789  <p>A live performance at WFMU for Dark Night o...
155066           1  22899  <p>Hip Hop, Old School type beat 2017, Trap Mu...

                                                  \
         listens                        producer
track_id
2           6073                             NaN
5           6073                             NaN
10         47632                             NaN
140         1300  Alec K. Refearn, Rob Pemberton
141         1304                             NaN
...          ...                             ...
154308     22334                         Fleslit
154309     22334                         Fleslit
154413      3777                   Julie Bennack
154414      3777                   Julie Bennack
155066      4524                        JBlanked

                                                             ...       track  \
                                                       tags  ... information
track_id                                                     ...
2                                                        []  ...         NaN
5                                                        []  ...         NaN
10                                                       []  ...         NaN
140                                                      []  ...         NaN
141                                                      []  ...         NaN
...                                                     ...  ...         ...
154308    ['fleslit', 'trap beat free use', 'trap beat f...  ...         NaN
154309    ['fleslit', 'trap beat free use', 'trap beat f...  ...         NaN
154413                                                   []  ...         NaN
154414                                                   []  ...         NaN
155066    ['old school beats', '2017 free instrumentals'...  ...         NaN

                                 \
         interest language_code
track_id
2            4656            en
5            1933            en
10          54881            en
140          1593            en
141           839            en
...           ...           ...
154308       3371           NaN
154309       4525           NaN
154413        809           NaN
154414        851           NaN
155066       2065           NaN

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
140       Attribution-Noncommercial-No Derivative Works ...    1299      NaN
141       Attribution-Noncommercial-No Derivative Works ...     725      NaN
...                                                     ...     ...      ...
154308                                          Attribution    2705      NaN
154309                                          Attribution    3589      NaN
154413    Creative Commons Attribution-NonCommercial-NoD...     676      NaN
154414    Creative Commons Attribution-NonCommercial-NoD...     788      NaN
155066                                          Attribution    1474      NaN

                                                                              \
         number publisher                                               tags
track_id
2             3       NaN                                                 []
5             6       NaN                                                 []
10            1       NaN                                                 []
140           2       NaN                                                 []
141           4       NaN                                                 []
...         ...       ...                                                ...
154308       17       NaN  ['fleslit', 'trap beat free use', 'trap beat f...
154309       18       NaN  ['fleslit', 'trap beat free use', 'trap beat f...
154413        9       NaN                                                 []
154414       10       NaN                                                 []
155066        3       NaN  ['old school beats', '2017 free instrumentals'...


                                title
track_id
2                                Food
5                          This World
10                            Freeway
140                Queen Of The Wires
141                              Ohio
...                               ...
154308                            MIA
154309                    A1 Symphony
154413                        Do Easy
154414    Dead Can Dance (uncensored)
155066                            Roy

[8000 rows x 52 columns]

In [8]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12],[13, 14, 15, 16, 17, 18]])

SUM = np.sum(a, axis=0)
SUM

array([21, 24, 27, 30, 33, 36])

In [9]:
a **2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144],
       [169, 196, 225, 256, 289, 324]])

In [10]:
SUMQ = np.sum(a**2, axis=0)
SUMQ

array([219, 264, 315, 372, 435, 504])

In [11]:
e = np.array([])

d = np.concatenate((e, SUMQ))
d

array([219., 264., 315., 372., 435., 504.])

In [12]:
[1] + [2]

[1, 2]

In [13]:
for i,j in zip(a,a**2):
    print(i)
    print(j)

[1 2 3 4 5 6]
[ 1  4  9 16 25 36]
[ 7  8  9 10 11 12]
[ 49  64  81 100 121 144]
[13 14 15 16 17 18]
[169 196 225 256 289 324]